// This file is part of Acala.

// Copyright (C) 2020-2025 Acala Foundation.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! # CDP Engine Module - generated by polka.codes
//!
//! ## Overview
//!
//! The core module of Honzon protocol. CDP engine is responsible for handle
//! internal processes about CDPs, including liquidation, settlement and risk
//! management.

#![cfg_attr(not(feature = "std"), no_std)]
#![allow(clippy::unused_unit)]
#![allow(clippy::upper_case_acronyms)]

use frame_support::{
	pallet_prelude::*,
	traits::{Get, UnixTime},
	transactional,
	PalletId,
};
use frame_system::pallet_prelude::*;
use codec::MaxEncodedLen;
use scale_info::TypeInfo;
use sp_runtime::{
	traits::{
		AccountIdConversion, One, Saturating, Zero, AtLeast32BitUnsigned, Bounded,
	},
	DispatchError, DispatchResult, FixedPointNumber, RuntimeDebug,
};
use sp_std::{marker::PhantomData, prelude::*};

mod mock;
mod tests;
pub mod weights;

pub use module::*;
pub use weights::WeightInfo;

/// Risk management params
#[derive(Encode, Decode, Clone, RuntimeDebug, PartialEq, Eq, Default, TypeInfo, MaxEncodedLen)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct RiskManagementParams<Balance> {
	/// Maximum total debit value generated from it, when reach the hard
	/// cap, CDP's owner cannot issue more stablecoin under the collateral
	/// type.
	pub maximum_total_debit_value: Balance,
	
	/// Liquidation ratio, when the collateral ratio of
	/// CDP under this collateral type is below the liquidation ratio, this
	/// CDP is unsafe and can be liquidated.
	pub liquidation_ratio: Option<Ratio>,
	
	/// Required collateral ratio, if it's set, cannot adjust the position
	/// of CDP so that the current collateral ratio is lower than the
	/// required collateral ratio.
	pub required_collateral_ratio: Option<Ratio>,
}

/// Ratio type for collateral calculations
pub type Ratio = sp_runtime::FixedU128;

/// Status of CDP
#[derive(Encode, Decode, Clone, RuntimeDebug, PartialEq, Eq, TypeInfo)]
pub enum CDPStatus {
	Safe,
	Unsafe,
	ChecksFailed(DispatchError),
}

/// Position info for a CDP
#[derive(Encode, Decode, Clone, RuntimeDebug, PartialEq, Eq, Default, TypeInfo, MaxEncodedLen)]
pub struct Position<Balance> {
	pub collateral: Balance,
	pub debit: Balance,
}

#[frame_support::pallet]
pub mod module {
	use super::*;

	#[pallet::config]
	pub trait Config: frame_system::Config {
		type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;

		/// Balance type used throughout the pallet
		type Balance: Member
			+ Parameter
			+ AtLeast32BitUnsigned
			+ Default
			+ Copy
			+ MaybeSerializeDeserialize
			+ MaxEncodedLen
			+ TypeInfo;

		/// The origin which may update risk management parameters. Root can
		/// always do this.
		type UpdateOrigin: EnsureOrigin<Self::RuntimeOrigin>;

		/// The default liquidation ratio for all collateral types of CDP
		#[pallet::constant]
		type DefaultLiquidationRatio: Get<Ratio>;

		/// The minimum debit value to avoid debit dust
		#[pallet::constant]
		type MinimumDebitValue: Get<Self::Balance>;

		/// Time used for computing era duration.
		type UnixTime: UnixTime;

		#[pallet::constant]
		type PalletId: Get<PalletId>;

		/// Weight information for the extrinsics in this module.
		type WeightInfo: WeightInfo;
	}

	#[pallet::error]
	pub enum Error<T> {
		/// The total debit value of specific collateral type already exceed the
		/// hard cap
		ExceedDebitValueHardCap,
		/// The collateral ratio below the required collateral ratio
		BelowRequiredCollateralRatio,
		/// The collateral ratio below the liquidation ratio
		BelowLiquidationRatio,
		/// The CDP must be unsafe status
		MustBeUnsafe,
		/// The CDP must be safe status
		MustBeSafe,
		/// Invalid collateral type
		InvalidCollateralType,
		/// Remain debit value in CDP below the dust amount
		RemainDebitValueTooSmall,
		/// No debit value in CDP so that it cannot be settled
		NoDebitValue,
		/// System has already been shutdown
		AlreadyShutdown,
		/// Must after system shutdown
		MustAfterShutdown,
		/// Collateral in CDP is not enough
		CollateralNotEnough,
		/// Convert debit value to debit balance failed
		ConvertDebitBalanceFailed,
		/// Collateral liquidation failed
		LiquidationFailed,
		/// Invalid rate
		InvalidRate,
	}

	#[pallet::event]
	#[pallet::generate_deposit(pub(crate) fn deposit_event)]
	pub enum Event<T: Config> {
		/// Liquidate the unsafe CDP.
		LiquidateUnsafeCDP {
			owner: T::AccountId,
			collateral_amount: T::Balance,
			bad_debt_value: T::Balance,
		},
		/// Settle the CDP has debit.
		SettleCDPInDebit {
			owner: T::AccountId,
		},
		/// The liquidation fee for specific collateral type updated.
		LiquidationRatioUpdated {
			new_liquidation_ratio: Option<Ratio>,
		},
		/// The required collateral penalty rate for specific collateral type updated.
		RequiredCollateralRatioUpdated {
			new_required_collateral_ratio: Option<Ratio>,
		},
		/// The hard cap of total debit value for specific collateral type updated.
		MaximumTotalDebitValueUpdated {
			new_total_debit_value: T::Balance,
		},
	}

	/// Mapping from valid collateral type to its risk management params
	#[pallet::storage]
	#[pallet::getter(fn collateral_params)]
	pub type CollateralParams<T: Config> = StorageValue<_, RiskManagementParams<T::Balance>, OptionQuery>;

	/// Positions of CDPs by account
	#[pallet::storage]
	#[pallet::getter(fn positions)]
	pub type Positions<T: Config> = StorageMap<_, Blake2_128Concat, T::AccountId, Position<T::Balance>, ValueQuery>;

	/// Timestamp in seconds of the last interest accumulation
	#[pallet::storage]
	#[pallet::getter(fn last_accumulation_secs)]
	pub type LastAccumulationSecs<T: Config> = StorageValue<_, u64, ValueQuery>;

	/// Emergency shutdown flag
	#[pallet::storage]
	#[pallet::getter(fn is_shutdown)]
	pub type IsShutdown<T: Config> = StorageValue<_, bool, ValueQuery>;

	#[pallet::genesis_config]
	#[derive(frame_support::DefaultNoBound)]
	pub struct GenesisConfig<T: Config> {
		pub collateral_params: RiskManagementParams<T::Balance>,
		pub _phantom: PhantomData<T>,
	}

	#[pallet::genesis_build]
	impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
		fn build(&self) {
			CollateralParams::<T>::put(&self.collateral_params);
		}
	}

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		fn on_initialize(now: BlockNumberFor<T>) -> Weight {
			// Accumulate interest logic would go here
			let now_as_secs: u64 = if now > One::one() {
				T::UnixTime::now().as_secs()
			} else {
				Default::default()
			};
			
			LastAccumulationSecs::<T>::put(now_as_secs);
			T::WeightInfo::on_initialize()
		}
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Update parameters related to risk management of CDP
		#[pallet::call_index(0)]
		#[pallet::weight(T::WeightInfo::set_collateral_params())]
		pub fn set_collateral_params(
			origin: OriginFor<T>,
			liquidation_ratio: Option<Ratio>,
			required_collateral_ratio: Option<Ratio>,
			maximum_total_debit_value: T::Balance,
		) -> DispatchResult {
			T::UpdateOrigin::ensure_origin(origin)?;

			let mut collateral_params = Self::collateral_params().unwrap_or_default();
			
			if liquidation_ratio != collateral_params.liquidation_ratio {
				collateral_params.liquidation_ratio = liquidation_ratio;
				Self::deposit_event(Event::LiquidationRatioUpdated {
					new_liquidation_ratio: liquidation_ratio,
				});
			}
			
			if required_collateral_ratio != collateral_params.required_collateral_ratio {
				collateral_params.required_collateral_ratio = required_collateral_ratio;
				Self::deposit_event(Event::RequiredCollateralRatioUpdated {
					new_required_collateral_ratio: required_collateral_ratio,
				});
			}
			
			if maximum_total_debit_value != collateral_params.maximum_total_debit_value {
				collateral_params.maximum_total_debit_value = maximum_total_debit_value;
				Self::deposit_event(Event::MaximumTotalDebitValueUpdated {
					new_total_debit_value: maximum_total_debit_value,
				});
			}
			
			CollateralParams::<T>::put(collateral_params);
			Ok(())
		}

		/// Emergency shutdown the system
		#[pallet::call_index(1)]
		#[pallet::weight(T::WeightInfo::emergency_shutdown())]
		pub fn emergency_shutdown(origin: OriginFor<T>) -> DispatchResult {
			T::UpdateOrigin::ensure_origin(origin)?;
			IsShutdown::<T>::put(true);
			Ok(())
		}

		/// Adjust position by adding/removing collateral and debit
		#[pallet::call_index(2)]
		#[pallet::weight(T::WeightInfo::adjust_position())]
		pub fn adjust_position(
			origin: OriginFor<T>,
			collateral_adjustment: T::Balance,
			debit_adjustment: T::Balance,
		) -> DispatchResult {
			let who = ensure_signed(origin)?;
			
			ensure!(
				CollateralParams::<T>::exists(),
				Error::<T>::InvalidCollateralType,
			);

			let mut position = Self::positions(&who);
			
			// Apply adjustments
			position.collateral = position.collateral.saturating_add(collateral_adjustment);
			position.debit = position.debit.saturating_add(debit_adjustment);

			// Validate the new position
			Self::check_position_valid(position.collateral, position.debit)?;

			// Update storage
			Positions::<T>::insert(&who, position);
			Ok(())
		}
	}
}

impl<T: Config> Pallet<T> {
	pub fn account_id() -> T::AccountId {
		T::PalletId::get().into_account_truncating()
	}

	pub fn get_liquidation_ratio() -> Result<Ratio, DispatchError> {
		let params = Self::collateral_params().ok_or(Error::<T>::InvalidCollateralType)?;
		Ok(params.liquidation_ratio.unwrap_or_else(T::DefaultLiquidationRatio::get))
	}

	pub fn required_collateral_ratio() -> Result<Option<Ratio>, DispatchError> {
		let params = Self::collateral_params().ok_or(Error::<T>::InvalidCollateralType)?;
		Ok(params.required_collateral_ratio)
	}

	pub fn maximum_total_debit_value() -> Result<T::Balance, DispatchError> {
		let params = Self::collateral_params().ok_or(Error::<T>::InvalidCollateralType)?;
		Ok(params.maximum_total_debit_value)
	}

	pub fn calculate_collateral_ratio(
		collateral_balance: T::Balance,
		debit_balance: T::Balance,
	) -> Ratio {
		if debit_balance.is_zero() {
			return Ratio::max_value();
		}
		
		Ratio::checked_from_rational(collateral_balance, debit_balance)
			.unwrap_or_else(Ratio::max_value)
	}

	pub fn check_cdp_status(
		collateral_amount: T::Balance,
		debit_amount: T::Balance,
	) -> CDPStatus {
		if debit_amount.is_zero() {
			return CDPStatus::Safe;
		}

		let collateral_ratio = Self::calculate_collateral_ratio(collateral_amount, debit_amount);
		match Self::get_liquidation_ratio() {
			Ok(liquidation_ratio) => {
				if collateral_ratio < liquidation_ratio {
					CDPStatus::Unsafe
				} else {
					CDPStatus::Safe
				}
			}
			Err(e) => CDPStatus::ChecksFailed(e),
		}
	}

	pub fn check_position_valid(
		collateral_balance: T::Balance,
		debit_balance: T::Balance,
	) -> DispatchResult {
		if !debit_balance.is_zero() {
			let collateral_ratio = Self::calculate_collateral_ratio(collateral_balance, debit_balance);

			// Check the required collateral ratio
			if let Some(required_collateral_ratio) = Self::required_collateral_ratio()? {
				ensure!(
					collateral_ratio >= required_collateral_ratio,
					Error::<T>::BelowRequiredCollateralRatio
				);
			}

			// Check the liquidation ratio
			let liquidation_ratio = Self::get_liquidation_ratio()?;
			ensure!(collateral_ratio >= liquidation_ratio, Error::<T>::BelowLiquidationRatio);

			// Check the minimum_debit_value
			ensure!(
				debit_balance >= T::MinimumDebitValue::get(),
				Error::<T>::RemainDebitValueTooSmall,
			);
		}

		Ok(())
	}

	/// Liquidate an unsafe CDP (simplified version)
	pub fn liquidate_unsafe_cdp(who: &T::AccountId) -> DispatchResult {
		let position = Self::positions(who);

		// Ensure the CDP is unsafe
		ensure!(
			matches!(
				Self::check_cdp_status(position.collateral, position.debit),
				CDPStatus::Unsafe
			),
			Error::<T>::MustBeUnsafe
		);

		// Clear the position (simplified liquidation)
		Positions::<T>::remove(who);

		Self::deposit_event(Event::LiquidateUnsafeCDP {
			owner: who.clone(),
			collateral_amount: position.collateral,
			bad_debt_value: position.debit,
		});

		Ok(())
	}

	/// Settle CDP has debit after system shutdown
	pub fn settle_cdp_has_debit(who: &T::AccountId) -> DispatchResult {
		ensure!(Self::is_shutdown(), Error::<T>::MustAfterShutdown);
		
		let position = Self::positions(who);
		ensure!(!position.debit.is_zero(), Error::<T>::NoDebitValue);

		// Clear the position (simplified settlement)
		Positions::<T>::remove(who);

		Self::deposit_event(Event::SettleCDPInDebit {
			owner: who.clone(),
		});

		Ok(())
	}
}