// This file is part of Acala.

// Copyright (C) 2020-2025 Acala Foundation.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Tests for CDP Engine pallet - generated by polka.codes

use super::*;
use frame_support::{
	assert_err, assert_noop, assert_ok,
	traits::{
		fungible::MutateHold,
		honzon::{Debit, DebitUnit},
	},
};
use mock::{
	dynamic_params, new_test_ext, set_shutdown, CDPEngine, MockEmergencyShutdown, Parameters,
	RuntimeOrigin, RuntimeParameters, Test,
};
use pallet_loans::BalanceAdjustment;

type Loans = pallet_loans::Pallet<Test>;
type Balances = pallet_balances::Pallet<Test>;

#[test]
fn set_collateral_params_works() {
	new_test_ext().execute_with(|| {
		let new_params = RiskManagementParams {
			maximum_total_debit_value: 1_000_000_000_000_000_000u128,
			interest_rate_per_sec: Rate::from_rational(1, 10000),
			liquidation_ratio: Ratio::from_rational(15, 10),
			liquidation_penalty: Rate::from_rational(1, 10000),
			required_collateral_ratio: Some(Ratio::from_rational(12, 10)),
		};
		frame_system::Pallet::<Test>::set_block_number(1);
		assert_noop!(
			Parameters::set_parameter(
				RuntimeOrigin::signed(1),
				RuntimeParameters::CdpEngine(
					dynamic_params::cdp_engine::Parameters::RiskManagementParams(
						dynamic_params::cdp_engine::RiskManagementParams,
						Some(new_params),
					),
				)
			),
			DispatchError::BadOrigin
		);
		assert_ok!(Parameters::set_parameter(
			RuntimeOrigin::root(),
			RuntimeParameters::CdpEngine(
				dynamic_params::cdp_engine::Parameters::RiskManagementParams(
					dynamic_params::cdp_engine::RiskManagementParams,
					Some(new_params),
				)
			),
		));

		let params = CDPEngine::risk_management_params();
		assert_eq!(params.liquidation_ratio, Ratio::from_rational(15, 10));
		assert_eq!(params.required_collateral_ratio, Some(Ratio::from_rational(12, 10)));
	});
}

#[test]
fn adjust_position_works() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(1);
		let account_id = 1u64;
		assert_ok!(Loans::adjust_position(
			&account_id,
			BalanceAdjustment::increase(1000),
			BalanceAdjustment::increase(150),
			Some(Rate::one()),
		));

		let position = Loans::positions(&account_id);
		assert_eq!(position.collateral, 1000u128);
		assert_eq!(position.debit.units.into_inner(), 150u128);
		assert_eq!(position.debit.stability_fee, Rate::one());
	});
}

#[test]
fn adjust_position_fails_with_insufficient_collateral_ratio() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(1);
		let account_id = 1u64;

		// Set required collateral ratio first
		let new_params = RiskManagementParams {
			maximum_total_debit_value: 1_000_000_000_000_000_000u128,
			interest_rate_per_sec: Rate::from_rational(1, 10000),
			liquidation_ratio: Ratio::from_rational(15, 10),
			liquidation_penalty: Rate::from_rational(1, 10000),
			required_collateral_ratio: Some(Ratio::from_rational(12, 10)),
		};
		assert_ok!(Parameters::set_parameter(
			RuntimeOrigin::root(),
			RuntimeParameters::CdpEngine(
				dynamic_params::cdp_engine::Parameters::RiskManagementParams(
					dynamic_params::cdp_engine::RiskManagementParams,
					Some(new_params),
				)
			),
		));

		// Try to create a position with low collateral ratio
		assert_err!(
			Loans::adjust_position(
				&account_id,
				BalanceAdjustment::increase(100), // low collateral
				BalanceAdjustment::increase(150), // high debit
				Some(Rate::one()),
			),
			Error::<Test>::BelowRequiredCollateralRatio
		);
	});
}

#[test]
fn emergency_shutdown_blocks_liquidation() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(1);
		let account_id = 1u64;
		// Create an unsafe position
		let unsafe_position = Position {
			collateral: 100u128,
			debit: Debit { units: DebitUnit::new(1000u128), stability_fee: Rate::one() },
		};
		pallet_loans::Positions::<Test>::insert(account_id, unsafe_position);
		pallet_loans::TotalDebitByStabilityFee::<Test>::insert(
			Rate::one(),
			unsafe_position.debit.units,
		);
		assert_ok!(Balances::hold(
			&pallet_loans::HoldReason::Collateral.into(),
			&account_id,
			unsafe_position.collateral,
		));

		assert!(!MockEmergencyShutdown::is_shutdown());

		set_shutdown(true);

		assert!(MockEmergencyShutdown::is_shutdown());
		assert_noop!(
			CDPEngine::liquidate(RuntimeOrigin::none(), account_id),
			Error::<Test>::AlreadyShutdown,
		);
	});
}

#[test]
fn liquidate_unsafe_cdp_works() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(1);
		let account_id = 1u64;

		// First create an unsafe position directly in storage
		let unsafe_position = Position {
			collateral: 100u128,
			debit: Debit { units: DebitUnit::new(1000u128), stability_fee: Rate::one() },
		};
		pallet_loans::Positions::<Test>::insert(account_id, unsafe_position);
		pallet_loans::TotalDebitByStabilityFee::<Test>::insert(
			Rate::one(),
			unsafe_position.debit.units,
		);
		assert_ok!(Balances::hold(
			&pallet_loans::HoldReason::Collateral.into(),
			&account_id,
			unsafe_position.collateral,
		));

		assert_ok!(CDPEngine::do_liquidate(account_id));

		// Position should be cleared
		let position = Loans::positions(&account_id);
		assert_eq!(position.collateral, 0u128);
		assert_eq!(position.debit.units.into_inner(), 0u128);
	});
}

#[test]
fn settle_cdp_works() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(1);
		let account_id = 1u64;

		// Create a position with debit and collateral
		assert_ok!(Loans::adjust_position(
			&account_id,
			BalanceAdjustment::increase(1000),
			BalanceAdjustment::increase(500),
			Some(Rate::one())
		));

		// Enable shutdown before settlement
		set_shutdown(true);

		assert_ok!(CDPEngine::do_settle(account_id));

		// Position should be cleared
		let position = Loans::positions(&account_id);
		assert_eq!(position.collateral, 500u128);
		assert_eq!(position.debit.units.into_inner(), 0u128);
	});
}

#[test]
fn on_initialize_works() {
	new_test_ext().execute_with(|| {
		frame_system::Pallet::<Test>::set_block_number(2);
		// Test that on_initialize runs without errors
		let weight = CDPEngine::on_initialize(2u64);
		assert!(weight.ref_time() > 0);

		// Check that timestamp is updated
		let timestamp = CDPEngine::last_accumulation_secs();
		assert!(timestamp > 0);
	});
}
