// generated by polka.codes
//! Mock runtime for `pallet-connections`.

use crate as pallet_connections;
use frame_support::{
    construct_runtime, parameter_types, PalletId,
    traits::{AsEnsureOriginWithArg, ConstU128, ConstU32, ConstU64, GenesisBuild, FindAuthor, ConstU8, BlockNumberProvider},
};
use sp_core::H256;
use sp_runtime::{
    testing::Header,
    traits::{BlakeTwo256, IdentityLookup, AccountIdConversion},
};
use crate::{VaultProvider, LiquidityRouter};
use frame_support::dispatch::{DispatchResult, DispatchError};

type UncheckedExtrinsic = frame_system::mocking::MockUncheckedExtrinsic<Test>;
type Block = frame_system::mocking::MockBlock<Test>;

construct_runtime!(
    pub enum Test where
        Block = Block,
        NodeBlock = Block,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        System: frame_system::{Pallet, Call, Config, Storage, Event<T>},
        Balances: pallet_balances::{Pallet, Call, Storage, Config<T>, Event<T>},
        Assets: pallet_assets::{Pallet, Call, Storage, Event<T>},
        Connections: pallet_connections::{Pallet, Call, Storage, Event<T>},
    }
);

parameter_types! {
    pub const BlockHashCount: u64 = 250;
    pub const SS58Prefix: u8 = 42;
}

impl frame_system::Config for Test {
    type BaseCallFilter = frame_support::traits::Everything;
    type BlockWeights = ();
    type BlockLength = ();
    type DbWeight = ();
    type RuntimeOrigin = RuntimeOrigin;
    type RuntimeCall = RuntimeCall;
    type Index = u64;
    type BlockNumber = u64;
    type Hash = H256;
    type Hashing = BlakeTwo256;
    type AccountId = u64;
    type Lookup = IdentityLookup<Self::AccountId>;
    type Header = Header;
    type RuntimeEvent = RuntimeEvent;
    type BlockHashCount = BlockHashCount;
    type Version = ();
    type PalletInfo = PalletInfo;
    type AccountData = pallet_balances::AccountData<u128>;
    type OnNewAccount = ();
    type OnKilledAccount = ();
    type SystemWeightInfo = ();
    type SS58Prefix = SS58Prefix;
    type OnSetCode = ();
    type MaxConsumers = ConstU32<16>;
}

impl pallet_balances::Config for Test {
    type MaxLocks = ();
    type MaxReserves = ();
    type ReserveIdentifier = [u8; 8];
    type Balance = u128;
    type RuntimeEvent = RuntimeEvent;
    type DustRemoval = ();
    type ExistentialDeposit = ConstU128<1>;
    type AccountStore = System;
    type WeightInfo = ();
    type FreezeIdentifier = ();
    type MaxFreezes = ();
    type RuntimeHoldReason = ();
    type MaxHolds = ();
}

impl pallet_assets::Config for Test {
    type RuntimeEvent = RuntimeEvent;
    type Balance = u128;
    type AssetId = u32;
    type AssetIdParameter = u32;
    type Currency = Balances;
    type CreateOrigin = AsEnsureOriginWithArg<frame_system::EnsureSigned<u64>>;
    type ForceOrigin = frame_system::EnsureRoot<u64>;
    type AssetDeposit = ConstU128<1>;
    type AssetAccountDeposit = ConstU128<10>;
    type MetadataDepositBase = ConstU128<1>;
    type MetadataDepositPerByte = ConstU128<1>;
    type ApprovalDeposit = ConstU128<1>;
    type StringLimit = ConstU32<50>;
    type Freezer = ();
    type Extra = ();
    type WeightInfo = ();
    type RemoveItemsLimit = ConstU32<1000>;
    type CallbackHandle = ();
}

pub struct MockVaultProvider;
impl VaultProvider<u64, u128, u32> for MockVaultProvider {
    fn deposit_collateral(_vault_id: &u32, _from: &u64, _amount: u128) -> DispatchResult { Ok(()) }
    fn withdraw_collateral(_vault_id: &u32, _to: &u64, _amount: u128) -> DispatchResult { Ok(()) }
    fn mint(_vault_id: &u32, to: &u64, amount: u128) -> DispatchResult {
        let stable_asset_id = 1;
        Assets::mint_into(stable_asset_id, to, amount).unwrap();
        Ok(())
    }
    fn repay(_vault_id: &u32, from: &u64, amount: u128) -> DispatchResult {
        let stable_asset_id = 1;
        Assets::burn_from(stable_asset_id, from, amount).unwrap();
        Ok(())
    }
    fn close_vault(_vault_id: &u32) -> DispatchResult { Ok(()) }
    fn has_debt(_vault_id: &u32) -> Result<bool, DispatchError> { Ok(false) }
}

pub struct MockLiquidityRouter;
impl LiquidityRouter<u64, u128, u32> for MockLiquidityRouter {
    type DestinationId = u32;
    fn deposit(_destination_id: Self::DestinationId, _connection_id: u32, _who: &u64, _amount: u128) -> DispatchResult { Ok(()) }
    fn withdraw(_destination_id: Self::DestinationId, _connection_id: u32, _who: &u64, _amount: u128) -> DispatchResult { Ok(()) }
    fn get_destination_account(_destination_id: Self::DestinationId) -> Result<u64, DispatchError> { Ok(99) } // 99 is the destination account
}

parameter_types! {
    pub const ConnectionsPalletId: PalletId = PalletId(*b"conpalet");
}

impl crate::Config for Test {
    type RuntimeEvent = RuntimeEvent;
    type Balance = u128;
    type VaultProvider = MockVaultProvider;
    type LiquidityRouter = MockLiquidityRouter;
    type GovernanceOrigin = frame_system::EnsureRoot<u64>;
    type ConnectionId = u32;
    type PalletId = ConnectionsPalletId;
}

pub fn new_test_ext() -> sp_io::TestExternalities {
    let mut t = frame_system::GenesisConfig::default().build_storage::<Test>().unwrap();
    let mut ext = sp_io::TestExternalities::new(t);
    ext.execute_with(|| System::set_block_number(1));
    ext
}
