// generated by polka.codes
//! Mock runtime for `pallet-connections`.

use crate as pallet_connections;
#[cfg(feature = "runtime-benchmarks")]
use crate::BenchmarkHelper;
use frame_support::{
	construct_runtime, derive_impl, parameter_types,
	traits::{fungibles::Mutate, AsEnsureOriginWithArg, ConstU128, ConstU32},
	PalletId,
};
use sp_core::H256;
use sp_runtime::{
	traits::{BlakeTwo256, IdentityLookup},
	BuildStorage, DispatchError, DispatchResult,
};

use crate::{LiquidityRouter, VaultProvider};
#[cfg(feature = "runtime-benchmarks")]
use frame_support::traits::tokens::fungibles::Inspect;
#[cfg(feature = "runtime-benchmarks")]
use frame_system::RawOrigin;
use std::{cell::RefCell, collections::BTreeMap};

type Block = frame_system::mocking::MockBlock<Test>;

construct_runtime!(
	pub enum Test
	{
		System: frame_system,
		Balances: pallet_balances,
		Assets: pallet_assets,
		Connections: pallet_connections,
	}
);

parameter_types! {
	pub const BlockHashCount: u64 = 250;
	pub const SS58Prefix: u8 = 42;
}

impl frame_system::Config for Test {
	type BaseCallFilter = frame_support::traits::Everything;
	type BlockWeights = ();
	type BlockLength = ();
	type DbWeight = ();
	type RuntimeOrigin = RuntimeOrigin;
	type RuntimeCall = RuntimeCall;
	type Nonce = u64;
	type Hash = H256;
	type Hashing = BlakeTwo256;
	type AccountId = u64;
	type Lookup = IdentityLookup<Self::AccountId>;
	type Block = Block;
	type RuntimeEvent = RuntimeEvent;
	type BlockHashCount = BlockHashCount;
	type Version = ();
	type PalletInfo = PalletInfo;
	type AccountData = pallet_balances::AccountData<u128>;
	type OnNewAccount = ();
	type OnKilledAccount = ();
	type SystemWeightInfo = ();
	type SS58Prefix = SS58Prefix;
	type OnSetCode = ();
	type MaxConsumers = ConstU32<16>;
	type RuntimeTask = ();
	type ExtensionsWeightInfo = ();
	type SingleBlockMigrations = ();
	type MultiBlockMigrator = ();
	type PreInherents = ();
	type PostInherents = ();
	type PostTransactions = ();
}

impl pallet_balances::Config for Test {
	type MaxLocks = ();
	type MaxReserves = ();
	type ReserveIdentifier = [u8; 8];
	type Balance = u128;
	type RuntimeEvent = RuntimeEvent;
	type DustRemoval = ();
	type ExistentialDeposit = ConstU128<1>;
	type AccountStore = System;
	type WeightInfo = ();
	type FreezeIdentifier = ();
	type MaxFreezes = ();
	type RuntimeHoldReason = ();
	type RuntimeFreezeReason = ();
	type DoneSlashHandler = ();
}

use sp_runtime::FixedU128;

#[derive_impl(pallet_assets::config_preludes::TestDefaultConfig as pallet_assets::pallet::DefaultConfig)]
impl pallet_assets::Config for Test {
	type RuntimeEvent = RuntimeEvent;
	type Balance = u128;
	type AssetId = u32;
	type AssetIdParameter = u32;
	type Currency = Balances;
	type CreateOrigin = AsEnsureOriginWithArg<frame_system::EnsureSigned<u64>>;
	type ForceOrigin = frame_system::EnsureRoot<u64>;
	type AssetDeposit = ConstU128<1>;
	type AssetAccountDeposit = ConstU128<10>;
	type MetadataDepositBase = ConstU128<1>;
	type MetadataDepositPerByte = ConstU128<1>;
	type ApprovalDeposit = ConstU128<1>;
	type StringLimit = ConstU32<50>;
	type RemoveItemsLimit = ConstU32<1000>;
}

#[derive(Default, Clone)]
pub struct Vault {
	pub collateral: u128,
	pub debt: u128,
}

thread_local! {
	static VAULTS: RefCell<BTreeMap<u32, Vault>> = RefCell::new(BTreeMap::new());
}

pub struct MockVaultProvider;
impl VaultProvider<u64, u128, u32, u32> for MockVaultProvider {
	type AssetId = u32;

	fn get_position(vault_id: &u32) -> Result<(u128, u128), DispatchError> {
		let vault = VAULTS.with(|v| v.borrow().get(vault_id).cloned().unwrap_or_default());
		Ok((vault.collateral, vault.debt))
	}

	fn deposit_collateral(vault_id: &u32, _from: &u64, amount: u128) -> DispatchResult {
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.entry(*vault_id).or_default();
			vault.collateral += amount;
		});
		Ok(())
	}
	fn withdraw_collateral(vault_id: &u32, _to: &u64, amount: u128) -> DispatchResult {
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.entry(*vault_id).or_default();
			vault.collateral =
				vault.collateral.checked_sub(amount).ok_or("Not enough collateral")?;
			Ok(())
		})
	}
	fn mint(vault_id: &u32, to: &u64, amount: u128) -> DispatchResult {
		let stable_asset_id = 1;
		Assets::mint_into(stable_asset_id as u32, to, amount).unwrap();
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.entry(*vault_id).or_default();
			vault.debt += amount;
		});
		Ok(())
	}
	fn repay(vault_id: &u32, from: &u64, amount: u128) -> DispatchResult {
		let stable_asset_id = 1;
		use frame_support::traits::tokens::{Fortitude, Precision, Preservation};
		Assets::burn_from(
			stable_asset_id as u32,
			from,
			amount,
			Preservation::Expendable,
			Precision::Exact,
			Fortitude::Polite,
		)
		.unwrap();
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.entry(*vault_id).or_default();
			vault.debt = vault.debt.checked_sub(amount).ok_or("Not enough debt to repay")?;
			Ok(())
		})
	}
	fn close_vault(vault_id: &u32) -> DispatchResult {
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.get(vault_id).ok_or("Vault not found")?;
			if vault.debt != 0 {
				return Err("Vault not empty".into());
			}
			vaults.remove(vault_id);
			Ok(())
		})
	}

	fn has_debt(vault_id: &u32) -> Result<bool, DispatchError> {
		let vault = VAULTS.with(|v| v.borrow().get(vault_id).cloned().unwrap_or_default());
		Ok(vault.debt > 0)
	}

	fn withdraw_all_collateral(vault_id: &u32, _: &u64) -> Result<(), DispatchError> {
		VAULTS.with(|v| {
			let mut vaults = v.borrow_mut();
			let vault = vaults.entry(*vault_id).or_default();
			vault.collateral = 0;
		});
		Ok(())
	}

	fn set_stability_fee(_: &u32, _: Option<FixedU128>) -> Result<(), DispatchError> {
		Ok(())
	}
}

thread_local! {
	static LIQUIDITY: RefCell<BTreeMap<(u32, u64), u128>> = RefCell::new(BTreeMap::new());
}

pub struct MockLiquidityRouter;
impl LiquidityRouter<u64, u128> for MockLiquidityRouter {
	type DestinationId = u32;

	fn deposit(destination_id: Self::DestinationId, who: &u64, amount: u128) -> DispatchResult {
		LIQUIDITY.with(|l| {
			let mut liquidity = l.borrow_mut();
			*liquidity.entry((destination_id, *who)).or_default() += amount;
		});
		Ok(())
	}

	fn withdraw(destination_id: Self::DestinationId, who: &u64, amount: u128) -> DispatchResult {
		LIQUIDITY.with(|l| {
			let mut liquidity = l.borrow_mut();
			let balance = liquidity.entry((destination_id, *who)).or_default();
			*balance = balance.checked_sub(amount).ok_or("not enough liquidity")?;
			Ok(())
		})
	}

	fn withdraw_all(destination_id: Self::DestinationId, who: &u64) -> Result<(), DispatchError> {
		LIQUIDITY.with(|l| {
			let mut liquidity = l.borrow_mut();
			liquidity.remove(&(destination_id, *who)).unwrap_or_default();
			Ok(())
		})
	}

	fn get_destination_account(_destination_id: Self::DestinationId) -> Result<u64, DispatchError> {
		Ok(99) // 99 is the destination account
	}
}

parameter_types! {
	pub const ConnectionsPalletId: PalletId = PalletId(*b"conpalet");
}

impl crate::Config for Test {
	type Currency = Balances;
	type Balance = u128;
	type CurrencyId = u32;
	type VaultProvider = MockVaultProvider;
	type LiquidityRouter = MockLiquidityRouter;
	type GovernanceOrigin = frame_system::EnsureRoot<u64>;
	type ConnectionId = u32;
	type PalletId = ConnectionsPalletId;
	type BlockNumberProvider = System;
	type BlockNumber = u64;
	type StableCurrencyId = ConstU32<1>;
	type Fungibles = Assets;
	type WeightInfo = ();
	#[cfg(feature = "runtime-benchmarks")]
	type BenchmarkHelper = BenchHelper;
}

pub fn new_test_ext() -> sp_io::TestExternalities {
	let mut t = frame_system::GenesisConfig::<Test>::default().build_storage().unwrap();

	pallet_balances::GenesisConfig::<Test> {
		balances: vec![(1, 1_000_000_000), (2, 1_000_000_000)],
		dev_accounts: None,
	}
	.assimilate_storage(&mut t)
	.unwrap();

	let mut ext = sp_io::TestExternalities::new(t);
	ext.execute_with(|| System::set_block_number(1));
	ext
}

#[cfg(feature = "runtime-benchmarks")]
pub struct BenchHelper;

#[cfg(feature = "runtime-benchmarks")]
impl BenchmarkHelper<u64, u128, u32, u32, u64> for BenchHelper {
	fn destination_id(seed: u32) -> u32 {
		seed.saturating_add(1)
	}

	fn collateral_amount() -> u128 {
		1_000
	}

	fn mint_amount() -> u128 {
		500
	}

	fn prepare_open(
		owner: &u64,
		_connection_id: u32,
		connection_account: &u64,
		_destination_id: u32,
		_collateral_amount: u128,
		_mint_amount: u128,
	) -> DispatchResult {
		let _ = connection_account;
		let stable_asset_id: u32 = 1;
		if !Assets::asset_exists(stable_asset_id.into()) {
			Assets::force_create(
				RawOrigin::Root.into(),
				stable_asset_id.into(),
				owner.clone(),
				true,
				1,
			)?;
		}
		Ok(())
	}

	fn set_block_number(block: u64) {
		System::set_block_number(block);
	}
}
