// generated by polka.codes
//! Mock runtime for `pallet-connections`.

use crate as pallet_connections;
#[cfg(feature = "runtime-benchmarks")]
use crate::BenchmarkHelper;
use frame_support::{
    construct_runtime, parameter_types, PalletId,
    traits::{AsEnsureOriginWithArg, ConstU128, ConstU32, ConstU64, GenesisBuild, FindAuthor, ConstU8, BlockNumberProvider},
};
use sp_core::H256;
use sp_runtime::{
    testing::Header,
    traits::{BlakeTwo256, IdentityLookup, AccountIdConversion},
};
use crate::{LiquidityRouter, VaultProvider};
use frame_support::dispatch::{DispatchError, DispatchResult};
use std::cell::RefCell;
use std::collections::BTreeMap;
#[cfg(feature = "runtime-benchmarks")]
use frame_system::RawOrigin;
#[cfg(feature = "runtime-benchmarks")]
use frame_support::traits::tokens::fungibles::Inspect;

type UncheckedExtrinsic = frame_system::mocking::MockUncheckedExtrinsic<Test>;
type Block = frame_system::mocking::MockBlock<Test>;

construct_runtime!(
    pub enum Test where
        Block = Block,
        NodeBlock = Block,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        System: frame_system::{Pallet, Call, Config, Storage, Event<T>},
        Balances: pallet_balances::{Pallet, Call, Storage, Config<T>, Event<T>},
        Assets: pallet_assets::{Pallet, Call, Storage, Event<T>},
        Connections: pallet_connections::{Pallet, Call, Storage, Event<T>},
    }
);

parameter_types! {
    pub const BlockHashCount: u64 = 250;
    pub const SS58Prefix: u8 = 42;
}

impl frame_system::Config for Test {
    type BaseCallFilter = frame_support::traits::Everything;
    type BlockWeights = ();
    type BlockLength = ();
    type DbWeight = ();
    type RuntimeOrigin = RuntimeOrigin;
    type RuntimeCall = RuntimeCall;
    type Index = u64;
    type BlockNumber = u64;
    type Hash = H256;
    type Hashing = BlakeTwo256;
    type AccountId = u64;
    type Lookup = IdentityLookup<Self::AccountId>;
    type Header = Header;
    type RuntimeEvent = RuntimeEvent;
    type BlockHashCount = BlockHashCount;
    type Version = ();
    type PalletInfo = PalletInfo;
    type AccountData = pallet_balances::AccountData<u128>;
    type OnNewAccount = ();
    type OnKilledAccount = ();
    type SystemWeightInfo = ();
    type SS58Prefix = SS58Prefix;
    type OnSetCode = ();
    type MaxConsumers = ConstU32<16>;
}

impl pallet_balances::Config for Test {
    type MaxLocks = ();
    type MaxReserves = ();
    type ReserveIdentifier = [u8; 8];
    type Balance = u128;
    type RuntimeEvent = RuntimeEvent;
    type DustRemoval = ();
    type ExistentialDeposit = ConstU128<1>;
    type AccountStore = System;
    type WeightInfo = ();
    type FreezeIdentifier = ();
    type MaxFreezes = ();
    type RuntimeHoldReason = ();
    type MaxHolds = ();
}

impl pallet_assets::Config for Test {
    type RuntimeEvent = RuntimeEvent;
    type Balance = u128;
    type AssetId = u32;
    type AssetIdParameter = u32;
    type Currency = Balances;
    type CreateOrigin = AsEnsureOriginWithArg<frame_system::EnsureSigned<u64>>;
    type ForceOrigin = frame_system::EnsureRoot<u64>;
    type AssetDeposit = ConstU128<1>;
    type AssetAccountDeposit = ConstU128<10>;
    type MetadataDepositBase = ConstU128<1>;
    type MetadataDepositPerByte = ConstU128<1>;
    type ApprovalDeposit = ConstU128<1>;
    type StringLimit = ConstU32<50>;
    type Freezer = ();
    type Extra = ();
    type WeightInfo = ();
    type RemoveItemsLimit = ConstU32<1000>;
    type CallbackHandle = ();
}

#[derive(Default, Clone)]
pub struct Vault {
    pub collateral: u128,
    pub debt: u128,
}

thread_local! {
    static VAULTS: RefCell<BTreeMap<u32, Vault>> = RefCell::new(BTreeMap::new());
}

pub struct MockVaultProvider;
impl VaultProvider<u64, u128, u32, u32> for MockVaultProvider {
    fn get_position(vault_id: &u32) -> Result<(u128, u128), DispatchError> {
        let vault = VAULTS.with(|v| v.borrow().get(vault_id).cloned().unwrap_or_default());
        Ok((vault.collateral, vault.debt))
    }

    fn deposit_collateral(vault_id: &u32, _from: &u64, amount: u128) -> DispatchResult {
        VAULTS.with(|v| {
            let mut vaults = v.borrow_mut();
            let vault = vaults.entry(*vault_id).or_default();
            vault.collateral += amount;
        });
        Ok(())
    }
    fn withdraw_collateral(vault_id: &u32, _to: &u64, amount: u128) -> DispatchResult {
        VAULTS.with(|v| {
            let mut vaults = v.borrow_mut();
            let vault = vaults.entry(*vault_id).or_default();
            vault.collateral = vault.collateral.checked_sub(amount).ok_or("Not enough collateral")?;
            Ok(())
        })
    }
    fn mint(vault_id: &u32, to: &u64, amount: u128) -> DispatchResult {
        let stable_asset_id = 1;
        Assets::mint_into(stable_asset_id.into(), to, amount).unwrap();
        VAULTS.with(|v| {
            let mut vaults = v.borrow_mut();
            let vault = vaults.entry(*vault_id).or_default();
            vault.debt += amount;
        });
        Ok(())
    }
    fn repay(vault_id: &u32, from: &u64, amount: u128) -> DispatchResult {
        let stable_asset_id = 1;
        Assets::burn_from(stable_asset_id.into(), from, amount).unwrap();
        VAULTS.with(|v| {
            let mut vaults = v.borrow_mut();
            let vault = vaults.entry(*vault_id).or_default();
            vault.debt = vault.debt.checked_sub(amount).ok_or("Not enough debt to repay")?;
            Ok(())
        })
    }
    fn close_vault(vault_id: &u32) -> DispatchResult {
        VAULTS.with(|v| {
            let mut vaults = v.borrow_mut();
            let vault = vaults.get(vault_id).ok_or("Vault not found")?;
            if vault.collateral != 0 || vault.debt != 0 {
                return Err("Vault not empty".into());
            }
            vaults.remove(vault_id);
            Ok(())
        })
    }
    fn has_debt(vault_id: &u32) -> Result<bool, DispatchError> {
        let vault = VAULTS.with(|v| v.borrow().get(vault_id).cloned().unwrap_or_default());
        Ok(vault.debt > 0)
    }
}

thread_local! {
    static LIQUIDITY: RefCell<BTreeMap<(u32, u64), u128>> = RefCell::new(BTreeMap::new());
}

pub struct MockLiquidityRouter;
impl LiquidityRouter<u64, u128> for MockLiquidityRouter {
    type DestinationId = u32;

    fn deposit(destination_id: Self::DestinationId, who: &u64, amount: u128) -> DispatchResult {
        LIQUIDITY.with(|l| {
            let mut liquidity = l.borrow_mut();
            *liquidity.entry((destination_id, *who)).or_default() += amount;
        });
        Ok(())
    }

    fn withdraw(destination_id: Self::DestinationId, who: &u64, amount: u128) -> DispatchResult {
        LIQUIDITY.with(|l| {
            let mut liquidity = l.borrow_mut();
            let balance = liquidity.entry((destination_id, *who)).or_default();
            *balance = balance.checked_sub(amount).ok_or("not enough liquidity")?;
            Ok(())
        })
    }

    fn withdraw_all(
        destination_id: Self::DestinationId,
        who: &u64,
    ) -> Result<u128, DispatchError> {
        LIQUIDITY.with(|l| {
            let mut liquidity = l.borrow_mut();
            let amount = liquidity.remove(&(destination_id, *who)).unwrap_or_default();
            Ok(amount)
        })
    }

    fn get_destination_account(
        _destination_id: Self::DestinationId,
    ) -> Result<u64, DispatchError> {
        Ok(99) // 99 is the destination account
    }
}

parameter_types! {
    pub const ConnectionsPalletId: PalletId = PalletId(*b"conpalet");
}

impl crate::Config for Test {
    type RuntimeEvent = RuntimeEvent;
    type Balance = u128;
    type CurrencyId = u32;
    type VaultProvider = MockVaultProvider;
    type LiquidityRouter = MockLiquidityRouter;
    type GovernanceOrigin = frame_system::EnsureRoot<u64>;
    type ConnectionId = u32;
    type PalletId = ConnectionsPalletId;
    type BlockNumberProvider = System;
    type WithdrawalTimeout = ConstU64<10>;
    type StableCurrencyId = ConstU32<1>;
    type Fungibles = Assets;
    #[cfg(feature = "runtime-benchmarks")]
    type BenchmarkHelper = BenchHelper;
}

pub fn new_test_ext() -> sp_io::TestExternalities {
    let mut t = frame_system::GenesisConfig::default().build_storage::<Test>().unwrap();
    let mut ext = sp_io::TestExternalities::new(t);
    ext.execute_with(|| System::set_block_number(1));
    ext
}

#[cfg(feature = "runtime-benchmarks")]
pub struct BenchHelper;

#[cfg(feature = "runtime-benchmarks")]
impl BenchmarkHelper<u64, u128, u32, u32, u64> for BenchHelper {
    fn destination_id(seed: u32) -> u32 {
        seed.saturating_add(1)
    }

    fn collateral_amount() -> u128 {
        1_000
    }

    fn mint_amount() -> u128 {
        500
    }

    fn prepare_open(
        owner: &u64,
        _connection_id: u32,
        connection_account: &u64,
        _destination_id: u32,
        _collateral_amount: u128,
        _mint_amount: u128,
    ) -> DispatchResult {
        let _ = connection_account;
        let stable_asset_id: u32 = 1;
        if !Assets::asset_exists(stable_asset_id.into()) {
            Assets::force_create(
                RawOrigin::Root.into(),
                stable_asset_id.into(),
                owner.clone(),
                true,
                1,
            )?;
        }
        Ok(())
    }

    fn set_block_number(block: u64) {
        System::set_block_number(block);
    }
}
