// generated by polka.codes
//! Tests for `pallet-connections`.

use crate::{mock::*, Error, Connection, ConnectionStatus};
use frame_support::{assert_noop, assert_ok};
use sp_runtime::traits::AccountIdConversion;

const USER_A: u64 = 1;
const USER_B: u64 = 2;
const COLLATERAL_AMOUNT: u128 = 100;
const MINT_AMOUNT: u128 = 50;
const DESTINATION_ID: u32 = 1;
const STABLE_ASSET_ID: u32 = 1;
const DESTINATION_ACCOUNT: u64 = 99;

fn setup_asset() {
    assert_ok!(Assets::create(
        RuntimeOrigin::signed(USER_A),
        STABLE_ASSET_ID.into(),
        USER_A,
        1
    ));
}

#[test]
fn open_connection_works() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        let connection = Connections::connections(0).unwrap();
        assert_eq!(connection.owner, USER_A);
        assert_eq!(connection.destination_id, DESTINATION_ID);
        assert_eq!(connection.status, ConnectionStatus::Active);

        assert_eq!(Connections::next_connection_id(), 1);

        let pallet_account = ConnectionsPalletId::get().into_account_truncating();
        assert_eq!(Assets::balance(STABLE_ASSET_ID, pallet_account), MINT_AMOUNT);
    });
}

#[test]
fn initiate_withdrawal_works() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        let withdrawal_amount = 20;
        assert_ok!(Connections::initiate_withdrawal(
            RuntimeOrigin::signed(USER_A),
            0,
            withdrawal_amount
        ));

        let connection = Connections::connections(0).unwrap();
        assert_eq!(
            connection.status,
            ConnectionStatus::WithdrawalInProgress { amount: withdrawal_amount }
        );
    });
}

#[test]
fn initiate_withdrawal_fails_for_not_owner() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        assert_noop!(
            Connections::initiate_withdrawal(RuntimeOrigin::signed(USER_B), 0, 20),
            Error::<Test>::NotOwner
        );
    });
}

#[test]
fn complete_withdrawal_works() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        let withdrawal_amount = 20;
        assert_ok!(Connections::initiate_withdrawal(
            RuntimeOrigin::signed(USER_A),
            0,
            withdrawal_amount
        ));

        // Simulate destination transferring funds back to pallet
        let pallet_account = ConnectionsPalletId::get().into_account_truncating();
        assert_ok!(Assets::mint_into(STABLE_ASSET_ID, &pallet_account, withdrawal_amount));

        assert_ok!(Connections::complete_withdrawal(
            RuntimeOrigin::signed(DESTINATION_ACCOUNT),
            0,
            withdrawal_amount
        ));

        let connection = Connections::connections(0).unwrap();
        assert_eq!(connection.status, ConnectionStatus::Active);
        // Initial mint + withdrawal amount - repaid amount
        assert_eq!(Assets::balance(STABLE_ASSET_ID, pallet_account), MINT_AMOUNT);
    });
}

#[test]
fn complete_withdrawal_fails_for_bad_origin() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        let withdrawal_amount = 20;
        assert_ok!(Connections::initiate_withdrawal(
            RuntimeOrigin::signed(USER_A),
            0,
            withdrawal_amount
        ));

        assert_noop!(
            Connections::complete_withdrawal(RuntimeOrigin::signed(USER_A), 0, withdrawal_amount),
            Error::<Test>::BadOrigin
        );
    });
}

#[test]
fn withdraw_collateral_works() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        assert_ok!(Connections::withdraw_collateral(RuntimeOrigin::signed(USER_A), 0, 10));
    });
}

#[test]
fn close_connection_works() {
    new_test_ext().execute_with(|| {
        setup_asset();
        assert_ok!(Connections::open_connection(
            RuntimeOrigin::signed(USER_A),
            DESTINATION_ID,
            COLLATERAL_AMOUNT,
            MINT_AMOUNT
        ));

        // In mock, has_debt is always false
        assert_ok!(Connections::close_connection(RuntimeOrigin::signed(USER_A), 0));
        assert!(Connections::connections(0).is_none());
    });
}
