// generated by polka.codes
//! Traits for `pallet-connections`.

use frame_support::dispatch::DispatchResult;
use sp_runtime::DispatchError;

/// Trait for managing vaults associated with connections.
pub trait VaultProvider<AccountId, Balance, VaultId> {
    fn create_vault(vault_id: VaultId, owner: &AccountId) -> DispatchResult;
    fn deposit_collateral(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
    fn withdraw_collateral(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
    fn mint(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
    fn repay(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
    fn close_vault(vault_id: &VaultId) -> DispatchResult;
    fn has_debt(vault_id: &VaultId) -> Result<bool, DispatchError>;
}

/// Trait for routing liquidity to various destinations.
pub trait LiquidityRouter<AccountId, Balance, ConnectionId> {
    /// The type of identifier for a destination.
    type DestinationId: frame_support::pallet_prelude::Member
        + frame_support::pallet_prelude::Parameter
        + Copy
        + frame_support::pallet_prelude::MaxEncodedLen;

    /// Deposit stables to a destination.
    fn deposit(
        destination_id: Self::DestinationId,
        connection_id: ConnectionId,
        who: &AccountId,
        amount: Balance,
    ) -> DispatchResult;

    /// Initiate a withdrawal of stables from a destination.
    /// The destination is expected to call back to `pallet-connections`.
    fn withdraw(
        destination_id: Self::DestinationId,
        connection_id: ConnectionId,
        who: &AccountId,
        amount: Balance,
    ) -> DispatchResult;

    /// Get the account ID of a destination.
    fn get_destination_account(
        destination_id: Self::DestinationId,
    ) -> Result<AccountId, DispatchError>;
}
