// generated by polka.codes

use sp_runtime::{DispatchError, DispatchResult};

pub trait LiquidityRouter<AccountId, Balance, ConnectionId> {
	/// The type of identifier for a destination.
	type DestinationId: frame_support::pallet_prelude::Member
		+ frame_support::pallet_prelude::Parameter
		+ Copy
		+ Default
		+ frame_support::pallet_prelude::MaxEncodedLen
		+ codec::Encode
		+ codec::Decode
		+ scale_info::TypeInfo
		+ sp_std::fmt::Debug
		+ PartialEq;
	fn get_destination_account(
		destination_id: Self::DestinationId,
	) -> Result<AccountId, DispatchError>;
	fn deposit(
		destination_id: Self::DestinationId,
		connection_id: ConnectionId,
		who: &AccountId,
		amount: Balance,
	) -> DispatchResult;
	fn withdraw(
		destination_id: Self::DestinationId,
		connection_id: ConnectionId,
		who: &AccountId,
		amount: Balance,
	) -> DispatchResult;
}

pub trait VaultProvider<AccountId, Balance, CurrencyId, VaultId> {
	type AssetId;
	fn create_vault(vault_id: VaultId, owner: &AccountId) -> DispatchResult;
	fn deposit_collateral(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
	fn withdraw_collateral(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
	fn mint(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
	fn repay(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
	fn close_vault(vault_id: &VaultId) -> DispatchResult;
	fn has_debt(vault_id: &VaultId) -> Result<bool, DispatchError>;
}
