// generated by polka.codes

use sp_runtime::{DispatchError, DispatchResult};

pub trait LiquidityDestination<AccountId, Balance> {
	fn deposit(who: &AccountId, amount: Balance) -> DispatchResult;
	fn withdraw(who: &AccountId, amount: Balance) -> DispatchResult;
	fn withdraw_all(who: &AccountId) -> DispatchResult;
}

pub trait LiquidityRouter<AccountId, Balance> {
	type DestinationId: frame_support::pallet_prelude::Member
		+ frame_support::pallet_prelude::Parameter
		+ Copy
		+ frame_support::pallet_prelude::MaxEncodedLen
		+ codec::Encode
		+ codec::Decode
		+ scale_info::TypeInfo
		+ sp_std::fmt::Debug
		+ PartialEq;
	fn get_destination_account(
		destination_id: Self::DestinationId,
	) -> Result<AccountId, DispatchError>;
	fn deposit(
		destination_id: Self::DestinationId,
		connection_account: &AccountId,
		amount: Balance,
	) -> DispatchResult;
	fn withdraw(
		destination_id: Self::DestinationId,
		connection_account: &AccountId,
		amount: Balance,
	) -> DispatchResult;
	fn withdraw_all(
		destination_id: Self::DestinationId,
		connection_account: &AccountId,
	) -> DispatchResult;
}

pub trait VaultProvider<AccountId, Balance, CurrencyId, VaultId> {
	type AssetId;
	fn deposit_collateral(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
	fn withdraw_collateral(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
	fn withdraw_all_collateral(vault_id: &VaultId, to: &AccountId) -> DispatchResult;
	fn mint(vault_id: &VaultId, to: &AccountId, amount: Balance) -> DispatchResult;
	fn repay(vault_id: &VaultId, from: &AccountId, amount: Balance) -> DispatchResult;
	fn get_position(vault_id: &VaultId) -> Result<(Balance, Balance), DispatchError>;
	fn set_stability_fee(
		vault_id: &VaultId,
		stability_fee: Option<super::Rate>,
	) -> DispatchResult;
	fn close_vault(vault_id: &VaultId) -> DispatchResult;
	fn has_debt(vault_id: &VaultId) -> Result<bool, DispatchError>;
}
