[package]
name = "pallet-cdp-engine"
version = "1.0.0"
authors = ["Acala Developers"]
edition = { workspace = true }

[dependencies]
codec = { workspace = true }
frame-support = { workspace = true, features = ["experimental"] }
frame-system = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
pallet-asset-conversion = { workspace = true }
pallet-loans = { workspace = true }
rand_chacha = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sp-application-crypto = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
pallet-cdp-treasury = { workspace = true }
pallet-parameters = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"num-traits/std",
	"pallet-asset-conversion/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-cdp-treasury/std",
	"pallet-loans/std",
	"pallet-parameters/std",
	"rand_chacha/std",
	"scale-info/std",
	"serde/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-loans/try-runtime",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-loans/runtime-benchmarks",
	"pallet-parameters/runtime-benchmarks",
]
