// This file is part of Acala.

// Copyright (C) 2020-2025 Acala Foundation.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for pallet_issuance_buffer
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-10-21, STEPS: `1`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HEAP SIZE: `262144`, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/acala
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_issuance_buffer
// --extrinsic
// *
// --output
// honzon/issuance-buffer/src/weights.rs
// --template=./templates/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_issuance_buffer`.
pub trait WeightInfo {
	fn fund() -> Weight;
	fn defund() -> Weight;
}

/// A default implementation for the `WeightInfo` trait.
impl WeightInfo for () {
    fn fund() -> Weight {
        Weight::from_parts(1, 1)
    }
    fn defund() -> Weight {
        Weight::from_parts(1, 1)
    }
}
