[package]
name = "pallet-loans"
version = "1.0.0"
license = "Apache-2.0"
authors = ["Acala Developers", "Parity Technologies <admin@parity.io>"]
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "FRAME loans pallet for managing Collateralized Debt Positions (CDPs)."

[dependencies]
codec = { workspace = true, features = ["max-encoded-len"] }
log = { workspace = true }
scale-info = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-arithmetic = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-asset-conversion = { workspace = true }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
pallet-cdp-treasury = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-asset-conversion/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-cdp-treasury/std",
	"scale-info/std",
	"serde/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-cdp-treasury/try-runtime",
	"sp-runtime/try-runtime",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
