// This file is part of Substrate.

// Copyright (C) 2020-2025 Acala Foundation.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! # CDP Treasury Pallet
//!
//! ## Overview
//!
//! The CDP Treasury pallet manages the surplus and debt generated by CDPs. It handles
//! excessive surplus and debt to maintain system health and stability. This pallet is
//! the sole authority for minting and burning the stable currency of the system.

#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::{
	pallet_prelude::*,
	traits::{
		fungibles::{Inspect, Mutate},
		honzon::{AuctionManager, CDPTreasury, CDPTreasuryExtended},
		tokens::{Balance as BalanceT, Preservation},
	},
	PalletId,
};
use frame_system::pallet_prelude::*;
use num_traits::ops::checked::CheckedRem;
use pallet_asset_conversion::Swap;
use sp_runtime::{
	traits::{AccountIdConversion, Saturating, Zero},
	DispatchResult,
};
use sp_std::prelude::*;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;

mod impls;
mod mock;
mod tests;
pub mod weights;

pub use pallet::*;
pub use weights::WeightInfo;

#[frame_support::pallet]
pub mod pallet {
	use super::*;

	#[pallet::config]
	pub trait Config: frame_system::Config {
		/// The origin which may update parameters and handle surplus.
		type UpdateOrigin: EnsureOrigin<Self::RuntimeOrigin>;

		/// The fungibles instance for managing assets.
		type Fungibles: Mutate<Self::AccountId, Balance = Self::Balance, AssetId = Self::CurrencyId>;

		/// The auction manager for handling surplus and debt auctions.
		type AuctionManagerHandler: AuctionManager<
			Self::AccountId,
			Balance = Self::Balance,
			CurrencyId = Self::CurrencyId,
		>;

		/// The balance type for amounts.
		type Balance: BalanceT;

		/// The currency ID type.
		type CurrencyId: Parameter + Member + Copy + MaybeSerializeDeserialize + Ord + MaxEncodedLen;

		/// The maximum number of auctions to create for selling collateral.
		#[pallet::constant]
		type MaxAuctionsCount: Get<u32>;

		/// The account ID of the treasury.
		#[pallet::constant]
		type TreasuryAccount: Get<Self::AccountId>;

		/// The CDP treasury's pallet ID, used for deriving its account ID.
		#[pallet::constant]
		type PalletId: Get<PalletId>;

		/// Weight information for the extrinsics in this pallet.
		type WeightInfo: WeightInfo;

		/// The currency ID of the stable currency.
		#[pallet::constant]
		type StableCurrencyId: Get<Self::CurrencyId>;

		/// The currency ID of the base currency.
		#[pallet::constant]
		type CollateralCurrencyId: Get<Self::CurrencyId>;

		/// The kind of asset which can be used for swapping.
		type AssetKind: Parameter + Member + MaxEncodedLen + Copy + From<Self::CurrencyId>;

		/// The swap instance for trading currencies.
		type Swap: Swap<Self::AccountId, Balance = Self::Balance, AssetKind = Self::AssetKind>;
	}

	#[pallet::error]
	pub enum Error<T> {
		/// The collateral amount of CDP treasury is not enough
		CollateralNotEnough,
		/// The surplus pool of CDP treasury is not enough
		SurplusPoolNotEnough,
		/// The debit pool of CDP treasury is not enough
		DebitPoolNotEnough,
		/// Cannot use collateral to swap stable
		CannotSwap,
	}

	#[pallet::event]
	#[pallet::generate_deposit(pub fn deposit_event)]
	pub enum Event<T: Config> {
		/// Expected collateral auction size updated.
		ExpectedCollateralAuctionSizeUpdated {
			/// The new expected size of each collateral auction.
			new_size: T::Balance,
		},
		/// Debit offset buffer updated.
		DebitOffsetBufferUpdated {
			/// The new buffer amount for the debit pool.
			amount: T::Balance,
		},
	}

	/// The expected size of each collateral auction.
	#[pallet::storage]
	#[pallet::getter(fn expected_collateral_auction_size)]
	pub type ExpectedCollateralAuctionSize<T: Config> = StorageValue<_, T::Balance, ValueQuery>;

	/// The total amount of system debt.
	#[pallet::storage]
	#[pallet::getter(fn debit_pool)]
	pub type DebitPool<T: Config> = StorageValue<_, T::Balance, ValueQuery>;

	/// The buffer amount of the debit pool that will not be offset by the surplus pool.
	#[pallet::storage]
	#[pallet::getter(fn debit_offset_buffer)]
	pub type DebitOffsetBuffer<T: Config> = StorageValue<_, T::Balance, ValueQuery>;

	/// Genesis configuration for the cdp-treasury pallet.
	#[pallet::genesis_config]
	#[derive(frame_support::DefaultNoBound)]
	pub struct GenesisConfig<T: Config> {
		/// The expected size of each collateral auction.
		pub expected_collateral_auction_size: T::Balance,
		pub _phantom: sp_std::marker::PhantomData<T>,
	}

	#[pallet::genesis_build]
	impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
		fn build(&self) {
			ExpectedCollateralAuctionSize::<T>::put(self.expected_collateral_auction_size);
		}
	}

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		/// On finalize, offset the surplus and debit pools.
		fn on_finalize(_now: BlockNumberFor<T>) {
			Self::offset_surplus_and_debit();
		}
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Extracts surplus to the treasury.
		///
		/// The dispatch origin of this call must be `UpdateOrigin`.
		///
		/// - `amount`: The amount of surplus to extract.
		#[pallet::call_index(0)]
		#[pallet::weight(T::WeightInfo::extract_surplus_to_treasury())]
		pub fn extract_surplus_to_treasury(
			origin: OriginFor<T>,
			#[pallet::compact] amount: T::Balance,
		) -> DispatchResult {
			T::UpdateOrigin::ensure_origin(origin)?;
			T::Fungibles::transfer(
				T::StableCurrencyId::get(),
				&Self::account_id(),
				&T::TreasuryAccount::get(),
				amount,
				Preservation::Expendable,
			)?;
			Ok(())
		}

		/// Auction the collateral not occupied by the auction.
		///
		/// The dispatch origin of this call must be `UpdateOrigin`.
		///
		/// - `amount`: collateral amount
		/// - `target`: target amount
		/// - `split`: split collateral to multiple auction according to the config size
		#[pallet::call_index(1)]
		#[pallet::weight(
			if *split {
				T::WeightInfo::auction_collateral(T::MaxAuctionsCount::get())
			} else {
				T::WeightInfo::auction_collateral(1)
			}
		)]
		pub fn auction_collateral(
			origin: OriginFor<T>,
			#[pallet::compact] amount: T::Balance,
			#[pallet::compact] target: T::Balance,
			split: bool,
		) -> DispatchResultWithPostInfo {
			T::UpdateOrigin::ensure_origin(origin)?;
			let created_auctions =
				<Self as CDPTreasuryExtended<T::AccountId>>::create_collateral_auctions(
					amount,
					target,
					Self::account_id(),
					split,
				)?;
			Ok(Some(T::WeightInfo::auction_collateral(created_auctions)).into())
		}

		/// Updates the expected size of each collateral auction.
		///
		/// The dispatch origin of this call must be `UpdateOrigin`.
		///
		/// - `size`: The expected size of each collateral auction.
		#[pallet::call_index(2)]
		#[pallet::weight((T::WeightInfo::set_expected_collateral_auction_size(), DispatchClass::Operational))]
		pub fn set_expected_collateral_auction_size(
			origin: OriginFor<T>,
			#[pallet::compact] size: T::Balance,
		) -> DispatchResult {
			T::UpdateOrigin::ensure_origin(origin)?;
			ExpectedCollateralAuctionSize::<T>::put(size);
			Self::deposit_event(Event::ExpectedCollateralAuctionSizeUpdated { new_size: size });
			Ok(())
		}

		/// Updates the debit offset buffer.
		///
		/// The dispatch origin of this call must be `UpdateOrigin`.
		///
		/// - `amount`: The new buffer amount for the debit pool.
		#[pallet::call_index(3)]
		#[pallet::weight(T::WeightInfo::set_debit_offset_buffer())]
		pub fn set_debit_offset_buffer(
			origin: OriginFor<T>,
			#[pallet::compact] amount: T::Balance,
		) -> DispatchResult {
			T::UpdateOrigin::ensure_origin(origin)?;
			DebitOffsetBuffer::<T>::mutate(|v| {
				if *v != amount {
					*v = amount;
					Self::deposit_event(Event::DebitOffsetBufferUpdated { amount });
				}
			});
			Ok(())
		}
	}
}

impl<T: Config> Pallet<T> {
	/// The account ID of the cdp-treasury pallet.
	pub fn account_id() -> T::AccountId {
		T::PalletId::get().into_account_truncating()
	}

	/// The total surplus of the system.
	pub fn surplus_pool() -> T::Balance {
		T::Fungibles::balance(T::StableCurrencyId::get(), &Self::account_id())
	}

	/// The total collateral amount of the cdp-treasury pallet.
	pub fn total_collaterals() -> T::Balance {
		T::Fungibles::balance(T::CollateralCurrencyId::get(), &Self::account_id())
	}

	/// The collateral amount not in an auction.
	pub fn total_collaterals_not_in_auction() -> T::Balance {
		Self::total_collaterals().saturating_sub(
			T::AuctionManagerHandler::get_total_collateral_in_auction(
				T::CollateralCurrencyId::get(),
			),
		)
	}

	/// Offsets the surplus and debit pools.
	fn offset_surplus_and_debit() {
		// The part of the debit pool that exceeds the debit offset buffer can be offset by the
		// surplus
		let offset_amount = sp_std::cmp::min(
			Self::debit_pool().saturating_sub(Self::debit_offset_buffer()),
			Self::surplus_pool(),
		);

		// Burn the amount that is equal to offset amount of stable currency.
		if !offset_amount.is_zero() {
			let res = Self::burn_debit(&Self::account_id(), offset_amount);
			match res {
				Ok(_) => {
					DebitPool::<T>::mutate(|debit| {
						*debit = debit
							.checked_sub(&offset_amount)
							.expect("offset = min(debit, surplus); qed")
					});
				},
				Err(e) => {
					log::warn!(
						target: "cdp-treasury",
						"get_swap_supply_amount: Attempt to burn surplus {:?} failed: {:?}, this is unexpected but should be safe",
						offset_amount, e
					);
				},
			}
		}
	}
}

/// Initializes the debit offset buffer.
pub struct InitializeDebitOffsetBuffer<T, GetBufferSize>(
	sp_std::marker::PhantomData<T>,
	sp_std::marker::PhantomData<GetBufferSize>,
);
impl<T: Config, GetBufferSize: Get<T::Balance>> frame_support::traits::OnRuntimeUpgrade
	for InitializeDebitOffsetBuffer<T, GetBufferSize>
{
	fn on_runtime_upgrade() -> Weight {
		let amount = GetBufferSize::get();
		DebitOffsetBuffer::<T>::mutate(|v| {
			if *v != amount {
				*v = amount;
				Pallet::<T>::deposit_event(Event::DebitOffsetBufferUpdated { amount });
			}
		});

		Weight::from_parts(0, 0)
	}
}
